/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Panels;

import NetWork.DataBaseMovie;
import User.Customer;
import Utility.Utilities;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author Administrador
 */
public class ExChange extends javax.swing.JFrame {

    /**
     * Creates new form ExChange
     */
    public ExChange() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSala1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSala1.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        btnSala1.setText("Sala1");
        btnSala1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSala1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        jLabel1.setText("Canjear 1 Entrada por 100 PopCoins");

        jButton1.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        jButton1.setText("Sala3");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        jButton2.setText("Sala2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        jButton3.setText("Sala4");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSala1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSala1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSala1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSala1ActionPerformed
        if(Integer.valueOf(Customer.popCoins) >= 100){
            int price;
        String nameMovie;
        int tickets = 1;
        String[] abc = new String[]{"A", "B", "C", "D", "E", "F"};
        price = 25;
        nameMovie = Utilities.name2DMovie1;
        int condition;
            do {
            String column = JOptionPane.showInputDialog(null, "Que Columna solicita '" +
                    "seleccione valores entre ("+abc[0]+", "+abc[1]+"....."+abc[abc.length-1]+")'", null, INFORMATION_MESSAGE);
            String line = JOptionPane.showInputDialog(null, "Que Fila solicita '" +
                    "seleccione valores entre ("+abc[0]+", "+abc[1]+"....."+abc[abc.length-1]+")'", null, INFORMATION_MESSAGE);
        if (column != null && line != null) {
            condition = DataBaseMovie.buyTicket("2DMovie1", column, line);
            switch(condition) {
                case 1 -> {
                    break;
                }
                case 2 -> {
                    tickets--;
                    JOptionPane.showMessageDialog(null, "Cancelo la compra", 
                            null, ERROR_MESSAGE);
                }
                case 0 -> {
                    JOptionPane.showMessageDialog(null, "Seleccion otro Asiento, Gracias");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "La compra se cancelo!",
                    null, ERROR_MESSAGE);
            break;
        }
            }while(condition == 0);
        JOptionPane.showMessageDialog(null, "Total gastado: "+price+"$\nMuchas gracias: "+Customer.name+" "+Customer.lastName+"\n"
                + "Por la compra de "+tickets+"boleto(s)", null, INFORMATION_MESSAGE);
        
        
        Utilities.commentMovie(nameMovie);
        Utilities.rankingMovie(nameMovie);
        } else {
            JOptionPane.showMessageDialog(null, "Requiere mas puntos para realizar la operacion", null, ERROR_MESSAGE);
        }
        
        
        
        this.dispose();
        
    

    }//GEN-LAST:event_btnSala1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                        
        if(Integer.valueOf(Customer.popCoins) >= 100){
        int price;
        String nameMovie;
        int tickets = 1;
        String[] abc = new String[]{"A", "B", "C", "D", "E", "F"};
        price = 25;
        nameMovie = Utilities.name2DMovie2;
        int condition;
            do {
            String column = JOptionPane.showInputDialog(null, "Que Columna solicita '" +
                    "seleccione valores entre ("+abc[0]+", "+abc[1]+"....."+abc[abc.length-1]+")'", null, INFORMATION_MESSAGE);
            String line = JOptionPane.showInputDialog(null, "Que Fila solicita '" +
                    "seleccione valores entre ("+abc[0]+", "+abc[1]+"....."+abc[abc.length-1]+")'", null, INFORMATION_MESSAGE);
        if (column != null && line != null) {
            condition = DataBaseMovie.buyTicket("2DMovie2", column, line);
            switch(condition) {
                case 1 -> {
                    break;
                }
                case 2 -> {
                    tickets--;
                    JOptionPane.showMessageDialog(null, "Cancelo la compra", 
                            null, ERROR_MESSAGE);
                }
                case 0 -> {
                    JOptionPane.showMessageDialog(null, "Seleccion otro Asiento, Gracias");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "La compra se cancelo!",
                    null, ERROR_MESSAGE);
            break;
        }
            }while(condition == 0);
        JOptionPane.showMessageDialog(null, "Total gastado: "+price+"$\nMuchas gracias: "+Customer.name+" "+Customer.lastName+"\n"
                + "Por la compra de "+tickets+"boleto(s)", null, INFORMATION_MESSAGE);
        
        
        Utilities.commentMovie(nameMovie);
        Utilities.rankingMovie(nameMovie);
        } else {
            JOptionPane.showMessageDialog(null, "Requiere mas puntos para realizar la operacion", null, ERROR_MESSAGE);
        }
        
        
        
        this.dispose();
        
        
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(Integer.valueOf(Customer.popCoins) >= 100){
        int price;
        String nameMovie;
        int tickets = 1;
        String[] abc = new String[]{"A", "B", "C", "D", "E", "F", "G", "H"};
        price = 35;
        nameMovie = Utilities.name3DMovie;
        int condition;
            do {
            String column = JOptionPane.showInputDialog(null, "Que Columna solicita '" +
                    "seleccione valores entre ("+abc[0]+", "+abc[1]+"....."+abc[abc.length-1]+")'", null, INFORMATION_MESSAGE);
            String line = JOptionPane.showInputDialog(null, "Que Fila solicita '" +
                    "seleccione valores entre ("+abc[0]+", "+abc[1]+"....."+abc[abc.length-1]+")'", null, INFORMATION_MESSAGE);
        if (column != null && line != null) {
            condition = DataBaseMovie.buyTicket("3DMovie", column, line);
            switch(condition) {
                case 1 -> {
                    break;
                }
                case 2 -> {
                    tickets--;
                    JOptionPane.showMessageDialog(null, "Cancelo la compra", 
                            null, ERROR_MESSAGE);
                }
                case 0 -> {
                    JOptionPane.showMessageDialog(null, "Seleccion otro Asiento, Gracias");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "La compra se cancelo!",
                    null, ERROR_MESSAGE);
            break;
        }
            }while(condition == 0);
        JOptionPane.showMessageDialog(null, "Total gastado: "+price+"$\nMuchas gracias: "+Customer.name+" "+Customer.lastName+"\n"
                + "Por la compra de "+tickets+"boleto(s)", null, INFORMATION_MESSAGE);
        
        
        Utilities.commentMovie(nameMovie);
        Utilities.rankingMovie(nameMovie);
        } else {
            JOptionPane.showMessageDialog(null, "Requiere mas puntos para realizar la operacion", null, ERROR_MESSAGE);
        }
        
        
        
        this.dispose();
        
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         if(Integer.valueOf(Customer.popCoins) >= 100){
        int price;
        String nameMovie;
        int tickets = 1;
        String[] abc = new String[]{"A", "B", "C", "D", "E", "F", "G", "H", "I", "J"};
        price = 45;
        nameMovie = Utilities.namePM;
        int condition;
            do {
            String column = JOptionPane.showInputDialog(null, "Que Columna solicita '" +
                    "seleccione valores entre ("+abc[0]+", "+abc[1]+"....."+abc[abc.length-1]+")'", null, INFORMATION_MESSAGE);
            String line = JOptionPane.showInputDialog(null, "Que Fila solicita '" +
                    "seleccione valores entre ("+abc[0]+", "+abc[1]+"....."+abc[abc.length-1]+")'", null, INFORMATION_MESSAGE);
        if (column != null && line != null) {
            condition = DataBaseMovie.buyTicket("PremiumMovie", column, line);
            switch(condition) {
                case 1 -> {
                    break;
                }
                case 2 -> {
                    tickets--;
                    JOptionPane.showMessageDialog(null, "Cancelo la compra", 
                            null, ERROR_MESSAGE);
                }
                case 0 -> {
                    JOptionPane.showMessageDialog(null, "Seleccion otro Asiento, Gracias");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "La compra se cancelo!",
                    null, ERROR_MESSAGE);
            break;
        }
            }while(condition == 0);
        JOptionPane.showMessageDialog(null, "Total gastado: "+price+"$\nMuchas gracias: "+Customer.name+" "+Customer.lastName+"\n"
                + "Por la compra de "+tickets+"boleto(s)", null, INFORMATION_MESSAGE);
        
        
        Utilities.commentMovie(nameMovie);
        Utilities.rankingMovie(nameMovie);
       } else {
            JOptionPane.showMessageDialog(null, "Requiere mas puntos para realizar la operacion", null, ERROR_MESSAGE);
        }
        
        
        
        this.dispose();
        
    }//GEN-LAST:event_jButton3ActionPerformed

 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExChange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSala1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
