/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Panels;

import NetWork.DataBaseData;
import com.mysql.jdbc.Connection;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Diego
 */
public class HomeScreenLoget extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public HomeScreenLoget() {
        initComponents();
        load2DMovie1();
       
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HourMorSala1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BuySala1 = new javax.swing.JButton();
        NameSala1 = new javax.swing.JLabel();
        ImageSala1 = new javax.swing.JLabel();
        GenreSala1 = new javax.swing.JLabel();
        RoomsBackground = new javax.swing.JLabel();
        Prices = new javax.swing.JLabel();
        Billboard = new javax.swing.JLabel();
        Gray = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameShow = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Team Tryhards 322");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        HourMorSala1.setText("a");
        getContentPane().add(HourMorSala1);
        HourMorSala1.setBounds(240, 220, 120, 20);

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 290, 110, 30);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 250, 120, 30);

        BuySala1.setText("Comprar");
        getContentPane().add(BuySala1);
        BuySala1.setBounds(270, 380, 100, 22);

        NameSala1.setText("a");
        getContentPane().add(NameSala1);
        NameSala1.setBounds(240, 190, 110, 20);
        getContentPane().add(ImageSala1);
        ImageSala1.setBounds(60, 160, 160, 240);

        GenreSala1.setText("a");
        getContentPane().add(GenreSala1);
        GenreSala1.setBounds(240, 340, 120, 20);

        RoomsBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RoomsBackground .jpeg"))); // NOI18N
        getContentPane().add(RoomsBackground);
        RoomsBackground.setBounds(-10, 130, 870, 630);

        Prices.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Prices.jpeg"))); // NOI18N
        getContentPane().add(Prices);
        Prices.setBounds(0, 720, 210, 50);

        Billboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BillboardTop.jpeg"))); // NOI18N
        getContentPane().add(Billboard);
        Billboard.setBounds(0, 50, 780, 80);

        Gray.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Gray.jpeg"))); // NOI18N
        getContentPane().add(Gray);
        Gray.setBounds(780, 50, 90, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PricesSign.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 766, 870, 150);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Yo Programo Bien, Sino llame a este Numero: 72414837");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 5, 460, 40);

        nameShow.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        getContentPane().add(nameShow);
        nameShow.setBounds(590, 10, 250, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Bienvenido:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(500, 10, 80, 30);

        setSize(new java.awt.Dimension(864, 943));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreenLoget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreenLoget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreenLoget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreenLoget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreenLoget().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Billboard;
    private javax.swing.JButton BuySala1;
    public javax.swing.JLabel GenreSala1;
    private javax.swing.JLabel Gray;
    public javax.swing.JLabel HourMorSala1;
    public javax.swing.JLabel ImageSala1;
    public javax.swing.JLabel NameSala1;
    private javax.swing.JLabel Prices;
    private javax.swing.JLabel RoomsBackground;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel nameShow;
    // End of variables declaration//GEN-END:variables

    private void load2DMovie1() {
        java.sql.Connection connection;
        String dbMovie = "SELECT NameMovie, Hour, Genre, Image FROM 2DMovie1";
        
        try {
            connection = DataBaseData.connect();
            PreparedStatement searchData = connection.prepareStatement(dbMovie);
            ResultSet resultSearch = searchData.executeQuery();
            if(resultSearch.next()) {
                NameSala1.setText(resultSearch.getString("NameMovie"));
                HourMorSala1.setText(resultSearch.getString("Hour"));
                GenreSala1.setText(resultSearch.getString("Genre"));
                Blob blob = resultSearch.getBlob("Image");
                byte[] data = blob.getBytes(1, (int) blob.length());
                BufferedImage img = null;
                    try {
                        img = ImageIO.read(new ByteArrayInputStream(data));
                    } catch (IOException e) {
                        Logger.getLogger(HomeScreenLoget.class.getName()).log(Level.SEVERE, null, e);
                    }
                    
                    ImageIcon icono = new ImageIcon(img);
                    Icon imagen = new ImageIcon(icono.getImage().getScaledInstance(ImageSala1.getWidth(), ImageSala1.getHeight(), Image.SCALE_DEFAULT));
                    ImageSala1.setIcon(imagen);
            }
            connection.close();
         
         
        } catch(SQLException e) {
            
            System.out.println(e);
        } 
    }
}
